<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

class LogRepository extends EntityRepository
{
    public function findAll()
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }
}
